node('master') {

   stage('Git checkout') {
      checkout scm
   }
   stage('Build') {
      // Run the maven build
      sh "ls"
      sh "cd JavaMentoring/module03/task11/sports-betting-application"
      sh "mvn clean deploy"
   }
}